<?php

/**
* Implements hook_mail().
*/
function drupalday_mail($key, &$message, $params) {
 switch ($key) {
   case 'contact_form':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('Contact form: @name', array('@name' => $params['name']));
     $message['body'][] = $params['name'];
     $message['body'][] = $params['surname'];
     $message['body'][] = $params['phone'];
     $message['body'][] = $params['mail'];
     $message['body'][] = $params['message'];
     break;
 }
}
